<a href="https://colab.research.google.com/github/satriasuryap/Data-Portofolios/blob/main/data_cleaning_projects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning Project

> Introduction

Hi everyone, my name is Satria Surya Prana, and this is the first Data Science project I did for my own portofolio, in this project I will be using "NBA games data"(source:https://www.kaggle.com/datasets/nathanlauga/nba-games/data) dataset more specifically the ranking.csv included in the dataset, If there are any critics or comments about my project please don't hesitate to do so any inputs will be taken seriously in hope to make me a better data engineer/scientist one day.


> Problem Identification

Looking at the dataset I can't help but to think that there are a few aspects that can be improved so it can be used for further analytics, and those aspects are:


1.   Will the data be more efficient if there are no column that has null value?
2.   Why is there a league_id while the game always runs in the same league?
3.   Will it be easier if the win/loss record be separated?
4.   Is there an easier way to identify which seasons the ranking is showing?

# Importing the Important Libraries for This Project

In [1]:

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

The libraries that is included on this projects are as follows, if anyone wanted to know what each libraries brings feel free to ask me!

# Data Preperation

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

We will be using the NBA Ranking datasets recieved from kaggle for this project which has 210342 rows and 13 columns.

In [11]:
data = pd.read_csv("/content/drive/MyDrive/nba_datasets/ranking.csv")
data

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612743,0,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,NaN
1,1610612763,0,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,NaN
2,1610612740,0,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,NaN
3,1610612756,0,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,NaN
4,1610612746,0,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,1610612765,0,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,NaN
210338,1610612738,0,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,NaN
210339,1610612753,0,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,NaN
210340,1610612755,0,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,NaN
210341,1610612749,0,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,NaN

# Data Cleaning and Pre-Processing

Just to be safe it is recomended to check for duplicates inside the dataframe with drop_duplicates() functions

In [12]:
data.drop_duplicates()

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612743,0,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,NaN
1,1610612763,0,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,NaN
2,1610612740,0,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,NaN
3,1610612756,0,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,NaN
4,1610612746,0,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,1610612765,0,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,NaN
210338,1610612738,0,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,NaN
210339,1610612753,0,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,NaN
210340,1610612755,0,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,NaN
210341,1610612749,0,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,NaN

Since we can see with our eyes that a column has a lot of Null values we will check whether it is fully null or not.

In [15]:
nan_count = data.isnull().sum()
print(nan_count)

TEAM_ID               0
LEAGUE_ID             0
SEASON_ID             0
STANDINGSDATE         0
CONFERENCE            0
TEAM                  0
G                     0
W                     0
L                     0
W_PCT                 0
HOME_RECORD           0
ROAD_RECORD           0
RETURNTOPLAY     206352
dtype: int64

And as we can see most of the data in the *RETURNTOPLAY* column has mostly null values it is safe for us to drop the column since it will not be affect any harm on the dataframe, and we will also drop the *LEAGUE_ID* column since every game on the NBA is played on the same league so it is safe to drop the column as well.

In [25]:
columns = ['LEAGUE_ID', 'RETURNTOPLAY']
dropped_data = data.drop(columns, axis = 1)
dropped_data

,TEAM_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,HOME_WIN,HOME_LOSE,ROAD_WIN,ROAD_LOSE
0,1610612743,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,10,3,9,8
1,1610612763,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,13,2,6,9
2,1610612740,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,13,4,6,8
3,1610612756,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,14,4,5,9
4,1610612746,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,11,7,8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,1610612765,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,17,24,12,29
210338,1610612738,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,16,25,9,32
210339,1610612753,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,19,22,4,37
210340,1610612755,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,10,31,9,32
210341,1610612749,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,10,31,5,36

On the *HOME_RECORD* and *ROAD_RECORD* column it is clearly stated on how much does the team win or lose with each home and away games, but won't it be easier if the two can be separated and maybe can be build a query in the future?

In [26]:
dropped_data[['HOME_WIN', 'HOME_LOSE']] = dropped_data['HOME_RECORD'].str.split('-', expand=True)

In [27]:
dropped_data[['ROAD_WIN', 'ROAD_LOSE']] = dropped_data['ROAD_RECORD'].str.split('-', expand=True)

In [28]:
dropped_data

,TEAM_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,HOME_WIN,HOME_LOSE,ROAD_WIN,ROAD_LOSE
0,1610612743,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,10,3,9,8
1,1610612763,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,13,2,6,9
2,1610612740,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,13,4,6,8
3,1610612756,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,14,4,5,9
4,1610612746,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,11,7,8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,1610612765,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,17,24,12,29
210338,1610612738,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,16,25,9,32
210339,1610612753,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,19,22,4,37
210340,1610612755,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,10,31,9,32
210341,1610612749,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,10,31,5,36

On the outsiders perspective it will be really hard to look at the data and point out on which seasons are these data? since a single season of the NBA goes from late October to the middle of April, so I think it will be easier if people can see which seasons are these rankings belong to.

In [30]:
conditions = [
    (dropped_data['SEASON_ID'] == 22013),(dropped_data['SEASON_ID'] == 22014),(dropped_data['SEASON_ID'] == 22015),
    (dropped_data['SEASON_ID'] == 22016),(dropped_data['SEASON_ID'] == 22017),(dropped_data['SEASON_ID'] == 22018),
    (dropped_data['SEASON_ID'] == 22019),(dropped_data['SEASON_ID'] == 22020),(dropped_data['SEASON_ID'] == 22021),
    (dropped_data['SEASON_ID'] == 22022)
    ]

values = ['13-14', '14-15', '15-16', '16-17', '17-18', '18-19', '19-20', '20-21', '21-22', '22-23']

dropped_data['SEASONS'] = np.select(conditions, values)

dropped_data

,TEAM_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,HOME_WIN,HOME_LOSE,ROAD_WIN,ROAD_LOSE,SEASONS
0,1610612743,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,10,3,9,8,22-23
1,1610612763,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,13,2,6,9,22-23
2,1610612740,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,13,4,6,8,22-23
3,1610612756,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,14,4,5,9,22-23
4,1610612746,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,11,7,8,7,22-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210337,1610612765,22013,2014-09-01,East,Detroit,82,29,53,0.354,17-24,12-29,17,24,12,29,13-14
210338,1610612738,22013,2014-09-01,East,Boston,82,25,57,0.305,16-25,9-32,16,25,9,32,13-14
210339,1610612753,22013,2014-09-01,East,Orlando,82,23,59,0.280,19-22,4-37,19,22,4,37,13-14
210340,1610612755,22013,2014-09-01,East,Philadelphia,82,19,63,0.232,10-31,9-32,10,31,9,32,13-14
210341,1610612749,22013,2014-09-01,East,Milwaukee,82,15,67,0.183,10-31,5-36,10,31,5,36,13-14

# Exporting the Cleaned Data to a new .csv file

And lastly, to conclude this Data Cleaning it is important to save the data you have been cleaning to a new .csv file so it can be used in the future for many purposes, and in this case we can just simply use the function of .to_csv("file name")

In [ ]:
dropped_data.to_csv('cleaned_ranking.csv')